[miners]
optiplex ansible_host=192.168.0.253 ansible_user=optiplex
lab0     ansible_host=192.168.0.79  ansible_user=lab0
lab1     ansible_host=192.168.0.80  ansible_user=lab1
lab2     ansible_host=192.168.0.62  ansible_user=lab2
lab3     ansible_host=192.168.0.63  ansible_user=lab3
lab4     ansible_host=192.168.0.65  ansible_user=lab4
lab5     ansible_host=192.168.0.75  ansible_user=lab5
lab6     ansible_host=192.168.0.77  ansible_user=lab6
labzbook ansible_host=192.168.0.78  ansible_user=labzbook

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

